### ISSUE TITLE
Initialize pyimagej not working on Windows

### ISSUE THREAD

**Issue by Perkins-1** [imagej/pyimagej#43] opened 2019-07-05 12:01 UTC
Hello i am quite new to coding.
I try to call a Fiji ImageJ (1.52n) Macro out of my Python (2.7.16) code using pyimagej.
While initializing (ij = imagej.init()) i got this error:

`ERROR 2019-07-05 13:38:03,541: Unable to import scyjava: PYJNIUS_JAR environment variable not defined.
Traceback (most recent call last):
  File "Compare_tsv_05_07_2019.py", line 9, in <module>
    ij = imagej.init()
  File "C:\ProgramData\Anaconda3\lib\site-packages\imagej\imagej.py", line 104, in init
    import imglyb
  File "C:\ProgramData\Anaconda3\lib\site-packages\imglyb\__init__.py", line 41, in <module>
    config, _ = _init_jvm_options()
  File "C:\ProgramData\Anaconda3\lib\site-packages\imglyb\__init__.py", line 36, in _init_jvm_options
    import scyjava
  File "C:\ProgramData\Anaconda3\lib\site-packages\scyjava\__init__.py", line 57, in <module>
    raise ImportError('Unable to import scyjava dependency jnius.')
ImportError: Unable to import scyjava dependency jnius.`

I dont have a clue how to interpret or solve this problem. Any solutions or explanations for me?
Thanks a lot

**Comment by ctrueden** [comment] 2019-08-22 16:57
@Perkins-1 Sorry for the delay in reply.

Firstly, pyimagej only works with Python 3, not Python 2.

Assuming you continue having problems with a Python-3-based environment:
- Are you using conda?
- Did you activate your conda environment?
- Are you using the latest release of pyimagej?

**Comment by Perkins-1** [comment] 2019-09-04 09:29
@ctrueden No problem, i am glad someone answered!
Yes i am using cona 4.7.11.

I have created and activated an environement. But i just dont understand the connection of the environment, python and imagej. I am quite new to the stuff :/

I am using Fiji ImageJ 1.52p (Java 1.8.0_172).

I updated Python to 3.7 but still got that problems.

**Comment by Perkins-1** [comment] 2019-09-04 09:49
@ctrueden Thanks htat you answered!

I installed python 3.7.3 with conda 4.7.10 and activated an environment. After that i installed the latest version of pyimagej.

Thats what i get:

>>> import imagej
>>> ij = imagej.init('D:\Fiji.app')
Added 394 JARs to the Java classpath.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda\lib\site-packages\imagej\imagej.py", line 104, in init
    import imglyb
  File "C:\ProgramData\Anaconda\lib\site-packages\imglyb\__init__.py", line 40, in <module>
    from .imglib_ndarray import ImgLibReferenceGuard as _ImgLibReferenceGuard
  File "C:\ProgramData\Anaconda\lib\site-packages\imglyb\imglib_ndarray.py", line 2, in <module>
    from imglyb import util
  File "C:\ProgramData\Anaconda\lib\site-packages\imglyb\util.py", line 23, in <module>
    Helpers                            = autoclass('net.imglib2.python.Helpers')
  File "C:\ProgramData\Anaconda\lib\site-packages\jnius\reflect.py", line 159, in autoclass
    c = find_javaclass(clsname)
  File "jnius\jnius_export_func.pxi", line 26, in jnius.find_javaclass
jnius.JavaException: Class not found b'net/imglib2/python/Helpers

**Comment by ctrueden** [comment] 2019-09-04 16:54
@Perkins-1 From your traceback, there is something weird about your environment... your Python packages are directly in `C:\ProgramData\Anaconda\lib\site-packages` but I believe they _should_ be located in `C:\ProgramData\Anaconda\envs\<your-environment>\lib/python3.7\site-packages`. Are you sure you have a conda environment active? I could be wrong—I am using macOS, not Windows—but the paths look suspicious to me.

What does `python -c 'import sys; print(sys.path)'` say from your active environment? For comparison, here is mine:

```
$ python -c 'import sys; print(sys.path)'
['', '/usr/local/miniconda3/envs/scijava/lib/python37.zip', '/usr/local/miniconda3/envs/scijava/lib/python3.7', '/usr/local/miniconda3/envs/scijava/lib/python3.7/lib-dynload', '/usr/local/miniconda3/envs/scijava/lib/python3.7/site-packages']
```

Here is how to create a clean new conda environment and use it:
```
conda create -n pyimagej pyimagej openjdk=8
conda activate pyimagej
python -c "import imagej; ij = imagej.init('D:\\Fiji.app'); print(ij.getVersion())"
```

Please make sure you use `conda` to install `pyimagej`—not `pip`.

**Comment by Perkins-1** [comment] 2019-09-05 10:11
@ctrueden Thanks again for the reply! 
I reinstalled conda made the environment first and installed it afterwards.

import sys; print(sys.path)
['', 'C:\\ProgramData\\Anaconda\\python37.zip', 'C:\\ProgramData\\Anaconda\\DLLs', 'C:\\ProgramData\\Anaconda\\lib', 'C:\\ProgramData\\Anaconda', 'C:\\Users\\Klaus Schäfer\\AppData\\Roaming\\Python\\Python37\\site-packages', 'C:\\ProgramData\\Anaconda\\lib\\site-packages', 'C:\\ProgramData\\Anaconda\\lib\\site-packages\\win32', 'C:\\ProgramData\\Anaconda\\lib\\site-packages\\win32\\lib', 'C:\\ProgramData\\Anaconda\\lib\\site-packages\\Pythonwin']

It felt like the porblem is my preset computer name. It has an "ä" inside.

In the end i got the same as before:

python -c "import imagej; ij = imagej.init('D:\\Fiji.app'); print(ij.getVersion())"
Added 394 JARs to the Java classpath.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Anaconda\envs\pyimagej\lib\site-packages\imagej\imagej.py", line 104, in init
    import imglyb
  File "C:\ProgramData\Anaconda\envs\pyimagej\lib\site-packages\imglyb\__init__.py", line 40, in <module>
    from .imglib_ndarray import ImgLibReferenceGuard as _ImgLibReferenceGuard
  File "C:\ProgramData\Anaconda\envs\pyimagej\lib\site-packages\imglyb\imglib_ndarray.py", line 2, in <module>
    from imglyb import util
  File "C:\ProgramData\Anaconda\envs\pyimagej\lib\site-packages\imglyb\util.py", line 23, in <module>
    Helpers                            = autoclass('net.imglib2.python.Helpers')
  File "C:\ProgramData\Anaconda\envs\pyimagej\lib\site-packages\jnius\reflect.py", line 159, in autoclass
    c = find_javaclass(clsname)
  File "jnius\jnius_export_func.pxi", line 26, in jnius.find_javaclass
jnius.JavaException: Class not found b'net/imglib2/python/Helpers'

**Comment by ctrueden** [comment] 2019-09-05 14:04
```
import sys; print(sys.path)
['', 'C:\ProgramData\Anaconda\python37.zip', 'C:\ProgramData\Anaconda\DLLs', 'C:\ProgramData\Anaconda\lib', 'C:\ProgramData\Anaconda', 'C:\Users\Klaus Schäfer\AppData\Roaming\Python\Python37\site-packages', 'C:\ProgramData\Anaconda\lib\site-packages', 'C:\ProgramData\Anaconda\lib\site-packages\win32', 'C:\ProgramData\Anaconda\lib\site-packages\win32\lib', 'C:\ProgramData\Anaconda\lib\site-packages\Pythonwin']
```

The above Python path still does not look like it is grounded in an environment.

I am installing Conda now into my Windows VM to see if I can reproduce.

**Comment by ctrueden** [comment] 2019-09-05 14:50
@Perkins-1 I installed miniconda3 using [Chocolatey](https://chocolatey.org), a useful package manager for Windows. This added an "Anaconda Powershell Prompt" to my start menu, which I then launched. After running `conda create -c conda-forge -n pyimagej pyimagej openjdk=8` and then `conda activate imagej`, here is my python path:
```
(pyimagej) PS>python -c 'import sys; print(sys.path)'
['', 'C:\\tools\\miniconda3\\envs\\pyimagej\\python37.zip', 'C:\\tools\\miniconda3\\envs\\pyimagej\\DLLs', 'C:\\tools\\miniconda3\\envs\\pyimagej\\lib', 'C:\\tools\\miniconda3\\envs\\pyimagej', 'C:\\tools\\miniconda3\\envs\\pyimagej\\lib\\site-packages']
```
As you can see, all of my paths are inside my pyimagej environment (`C:\tools\miniconda3\envs\pyimagej` ), whereas yours are not. This tells me you are not running from inside an environment. Maybe your pyimagej environment is not active, or perhaps you are somehow using a different python executable.

I ran into one other difficulty when running pyimagej on Windows:
```
(pyimagej) PS>python -c 'import imagej; ij = imagej.init(); print(ij.getVersion())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\tools\miniconda3\envs\pyimagej\lib\site-packages\imagej\imagej.py", line 104, in init
    import imglyb
  File "C:\tools\miniconda3\envs\pyimagej\lib\site-packages\imglyb\__init__.py", line 38, in <module>
    config, _ = _init_jvm_options()
  File "C:\tools\miniconda3\envs\pyimagej\lib\site-packages\imglyb\__init__.py", line 33, in _init_jvm_options
    import scyjava
  File "C:\tools\miniconda3\envs\pyimagej\lib\site-packages\scyjava\__init__.py", line 122, in <module>
    jnius = _init_jvm()
  File "C:\tools\miniconda3\envs\pyimagej\lib\site-packages\scyjava\__init__.py", line 113, in _init_jvm
    import jnius
  File "C:\tools\miniconda3\envs\pyimagej\lib\site-packages\jnius\__init__.py", line 12, in <module>
    from .jnius import *  # noqa
ImportError: DLL load failed: The specified module could not be found.
```

This problem is that `jvm.dll` is not on the path, but it needs to be. I worked around this issue as follows:
```
(pyimagej) PS>$env:Path += ";C:\tools\miniconda3\envs\pyimagej\Library\jre\bin\server"
```

And then it worked for me:
(pyimagej) PS>python -c 'import imagej; ij = imagej.init(); print(ij.getVersion())'
log4j:WARN No appenders could be found for logger (org.bushe.swing.event.EventService).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Sep 05, 2019 7:46:21 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
2.0.0-rc-71
```
(The `Could not open/create prefs` warning is a known issue with ImageJ on Windows, and can be safely ignored.)

**Comment by Perkins-1** [comment] 2019-09-06 08:42
Thanks for the time you spend for me and this problem!

My env path should be right now:

['',` 'C:\\ProgramData\\Anaconda\\envs\\pyimagej\\python37.zip', 'C:\\ProgramData\\Anaconda\\envs\\pyimagej\\DLLs', 'C:\\ProgramData\\Anaconda\\envs\\pyimagej\\lib', 'C:\\ProgramData\\Anaconda\\envs\\pyimagej', 'C:\\Users\\Klaus Schäfer\\AppData\\Roaming\\Python\\Python37\\site-packages', 'C:\\ProgramData\\Anaconda\\envs\\pyimagej\\lib\\site-packages']

I got the difficulty as you descriebed with the jvm.dll as well. I added my path to your conclusion ($env:Path += ";C:\ProgramData\Anaconda\envs\pyimagej\Library\jre\bin\server") but i didnt wor out:

> (pyimagej) PS C:\Windows\system32> $env:Path += ";C:\ProgramData\Anaconda\envs\pyimagej\Library\jre\bin\server"
(pyimagej)` PS C:\Windows\system32> python -c 'import imagej; ij = imagej.init(); print(ij.getVersion())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Anaconda\envs\pyimagej\lib\site-packages\imagej\imagej.py", line 104, in init
    import imglyb
  File "C:\ProgramData\Anaconda\envs\pyimagej\lib\site-packages\imglyb\__init__.py", line 38, in <module>
    config, _ = _init_jvm_options()
  File "C:\ProgramData\Anaconda\envs\pyimagej\lib\site-packages\imglyb\__init__.py", line 33, in _init_jvm_options
    import scyjava
  File "C:\ProgramData\Anaconda\envs\pyimagej\lib\site-packages\scyjava\__init__.py", line 122, in <module>
    jnius = _init_jvm()
  File "C:\ProgramData\Anaconda\envs\pyimagej\lib\site-packages\scyjava\__init__.py", line 64, in _init_jvm
    mvn = str(subprocess.check_output(['mvn', '-v']))
  File "C:\ProgramData\Anaconda\envs\pyimagej\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "C:\ProgramData\Anaconda\envs\pyimagej\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\ProgramData\Anaconda\envs\pyimagej\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda\envs\pyimagej\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

Still thankfull for the support!

**Comment by ctrueden** [comment] 2019-09-06 12:51
> ```
> File "C:\ProgramData\Anaconda\envs\pyimagej\lib\site-packages\scyjava_init.py", line 64, in _init_jvm
> ```

The relevant line of code from `scyjava` is:
```python
mvn = str(subprocess.check_output(['mvn', '-v']))
```
So the issue is that your environment does not have `mvn` on the path.

What does `mvn -V` say from your PowerShell prompt with pyimagej environment active? I don't have access to my Windows VM at the moment, but can check it later also once I arrive at the office. In the meantime, here is what my macOS system says:
```
$ mvn -V
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T13:41:47-05:00)
Maven home: /usr/local/miniconda3/envs/scijava/opt/maven
Java version: 1.8.0_192, vendor: Azul Systems, Inc., runtime: /usr/local/miniconda3/envs/scijava/jre
```

As you can see, both Maven and Java are available from inside the environment.

**Comment by Perkins-1** [comment] 2019-09-06 13:32
Hey,
the mvn path seems wrong:


```
(pyimagej) PS C:\Windows\system32> $ mvn -V
In Zeile:1 Zeichen:1`
+ $ mvn -V
+ ~
    + CategoryInfo          : ObjectNotFound: ($:String) [], CommandNotFoundException


```

**Comment by ctrueden** [comment] 2019-09-06 15:27
@Perkins-1 I investigated further in my Windows VM.

The short story is: I [found and fixed some bugs](https://github.com/scijava/scyjava/commit/35010bb6d0634ee6942275440b915d458eb419b3) and released a new scyjava 0.2.3 to PyPI. The conda version should catch up in the next day or so.

With scyjava 0.2.3:
* Detecting JAVA_HOME using Maven should work now using the Conda Maven (fixes `FileNotFoundError: [WinError 2]`).
* The `$Env:Path +=` hack is no longer needed (fixes `ImportError: DLL load failed`).

If you want to give it a try immediately, you can upgrade from inside your activated environment:
```
pip install scyjava==0.2.3
```

And then try using pyimagej again:
```
python -c 'import imagej; ij = imagej.init(); print(ij.getVersion())'
```

If you still have problems, you could try enabling debug logging to see if any more useful information is printed:
```
python -c 'import logging; logging.basicConfig(level=logging.DEBUG); import imagej; ij = imagej.init(); print(ij.getVersion())'
```

Thank you for being a Windows guinea pig! 🐹

**Comment by Perkins-1** [comment] 2019-09-10 09:39
@ctrueden thank you for the update! After installing i still got problems:
```

  File "<string>", line 1, in <module>
  File "C:\ProgramData\Anaconda\envs\pyimagej\lib\site-packages\imagej\imagej.py", line 104, in init
    import imglyb
  File "C:\ProgramData\Anaconda\envs\pyimagej\lib\site-packages\imglyb\__init__.py", line 40, in <module>
    from .imglib_ndarray import ImgLibReferenceGuard as _ImgLibReferenceGuard
  File "C:\ProgramData\Anaconda\envs\pyimagej\lib\site-packages\imglyb\imglib_ndarray.py", line 2, in <module>
    from imglyb import util
  File "C:\ProgramData\Anaconda\envs\pyimagej\lib\site-packages\imglyb\util.py", line 23, in <module>
    Helpers                            = autoclass('net.imglib2.python.Helpers')
  File "C:\ProgramData\Anaconda\envs\pyimagej\lib\site-packages\jnius\reflect.py", line 159, in autoclass
    c = find_javaclass(clsname)
  File "jnius\jnius_export_func.pxi", line 26, in jnius.find_javaclass
jnius.JavaException: Class not found b'net/imglib2/python/Helpers'
```
I enabled debugging and received a lot of Info´s. These could be important:
```

DEBUG:scyjava:No PYJNIUS_JAR environment variable
DEBUG:scyjava:PYJNIUS_JAR still unknown; falling back to default path
DEBUG:scyjava:PYJNIUS_JAR found at "C:\ProgramData\Anaconda\envs\pyimagej\share\pyjnius\pyjnius.jar"
DEBUG:scyjava:Checking JAVA_HOME environment variable
DEBUG:scyjava:No JAVA_HOME environment variable
DEBUG:scyjava:JAVA_HOME still unknown; checking with Maven
DEBUG:scyjava:Maven said: b'Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)\nMaven home: C:\\ProgramData\\Anaconda\\envs\\pyimagej\\Library\\bin\\..\nJava version: 1.8.0_192, vendor: Azul Systems, Inc., runtime: C:\\ProgramData\\Anaconda\\envs\\pyimagej\\Library\\jre\nDefault locale: de_DE, platform encoding: Cp1252\nOS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"\n'
```

Thanks for all your work! To be continued?

**Comment by ctrueden** [comment] 2019-09-10 14:50
Those DEBUG messages look good. The `PYJNIUS_JAR` is autoset correctly. The `JAVA_HOME` detection successfully invokes the Conda environment's Maven and the Java runtime is visible there in the `runtime: ` part. It looks like the Java runtime boots up.

Maybe your JAR cache isn't 100% formed? Do you have a `imglib2-imglyb-0.3.0.jar` with size 31858 bytes?
```
(pyimagej) PS>ls ~\.jgo\net\imagej\imagej\RELEASE+net.imglib-imglib2-imglyb-0.3.0\imglib2-imglyb-0.3.0.jar


    Directory: C:\Users\curtis\.jgo\net\imagej\imagej\RELEASE+net.imglib-imglib2-imglyb-0.3.0


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a---l         9/5/2019   7:21 AM          31858 imglib2-imglyb-0.3.0.jar
```

**Comment by Perkins-1** [comment] 2019-09-11 08:22
@ctrueden hey chris. the JAR´s got the right size. I deleted and downloaded them but no changes. Still receiving the same error:

```
(pyimagej) PS C:\Windows\system32> python -c "import imagej; ij = imagej.init('D:\\Fiji.app'); print(ij.getVersion())"
Added 394 JARs to the Java classpath.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Anaconda\envs\pyimagej\lib\site-packages\imagej\imagej.py", line 104, in init
    import imglyb
  File "C:\ProgramData\Anaconda\envs\pyimagej\lib\site-packages\imglyb\__init__.py", line 40, in <module>
    from .imglib_ndarray import ImgLibReferenceGuard as _ImgLibReferenceGuard
  File "C:\ProgramData\Anaconda\envs\pyimagej\lib\site-packages\imglyb\imglib_ndarray.py", line 2, in <module>
    from imglyb import util
  File "C:\ProgramData\Anaconda\envs\pyimagej\lib\site-packages\imglyb\util.py", line 23, in <module>
    Helpers                            = autoclass('net.imglib2.python.Helpers')
  File "C:\ProgramData\Anaconda\envs\pyimagej\lib\site-packages\jnius\reflect.py", line 159, in autoclass
    c = find_javaclass(clsname)
  File "jnius\jnius_export_func.pxi", line 26, in jnius.find_javaclass
jnius.JavaException: Class not found b'net/imglib2/python/Helpers'
```

Seems like i need Ubuntu :)

**Comment by ctrueden** [comment] 2019-09-11 14:29
@Perkins-1 Could you please try `imagej.init()` (rather than `imagej.init('D:\\Fiji.app')`) to see if that makes any difference? On my Windows VM, I was testing only with the remote bootstrapping, not wrapping a local Fiji install.

One workaround you could try is to copy the `imglib2-imglyb-0.3.0.jar` into your `D:\\Fiji.app\\jars` folder. It is not supposed to be necessary, but it might avoid the issue for you.

**Comment by elevans** [comment] 2021-03-22 21:48
@Perkins-1 We have since moved pyimagej's java bridge from `pyjnius` to `JPype`. I'm closing this issue for now, but if you're still having issues please feel free to re-open this.

**Closed by elevans** 2021-03-22 21:48 UTC
Labels: priority:medium, pyjnius
