### ISSUE TITLE
pyimagej initialization interferes with python multiprocessing

### ISSUE THREAD

**Issue by jluethi** [imagej/pyimagej#37] opened 2019-05-24 11:45 UTC
I am trying to parallelize a python program that uses pyimagej for stitching of images. For this purpose, I'm using python multiprocessing. When imagej is initialized within the process, it interferes with the process terminating normally. Here is a simple example:

```
import imagej
from multiprocessing import Pool

def f(x):
    ij = imagej.init('/Applications/Fiji.app')
    print(x)

with Pool(processes=2) as pool:
    for i in range(10):
        pool.apply_async(f, args=(i,))

    pool.close()
    pool.join()
```

When the imagej initialization is commented out, this script prints:
```
0
1
2
3
4
5
6
7
8
9

Process finished with exit code 0
```

When the imagej initialization is not commented out, it prints:
```
Added 379 JARs to the Java classpath.
Added 379 JARs to the Java classpath.
0
1

Process finished with exit code 0
```
For a reason I don't understand, the imagej initialization leads to the process terminating with exit code 0 after running just one round per process (2 instead of 10 total).

Any idea what is causing this? Looking at the pyimagej api, there does not seem to be a way to turn off the VM from pyimagej once it is initialized. This would be very helpful to allow for parallelization of workflows via multiprocessing.

If imagej is initialized outside of the function being run, then it does not lead to this behavior. But it constantly grows in memory usage. Therefore, it would be great to be able to initialize per process and have the whole process, together with all the pyimagej memory usage, shut down again at the end.

PS:
Also, this is tangentially related to the discussion here [in the image.sc forum](https://forum.image.sc/t/pyimagej-outofmemoryerror-possibility-to-re-initialize/25928), but I thought this issue is specific and low-level enough to be a github issue and not a forum discussion. If you prefer to have those posts there, let me know, I'm happy to post it in the forum.

**Comment by ctrueden** [comment] 2019-05-24 19:32
You can only load the JVM once for the lifetime of the Python process. Well, maybe there are ways around that limitation, but loading it more than once is non-trivial. Once the JVM is loaded, it is loaded.

(As an aside: you _can_ initialize more than one ImageJ context for that JVM... but I'd typically recommend against doing that. Each context operates independently, and in particular, only one context at a time can do ImageJ1ish things, so you probably don't want to make multiple ImageJs. That said, if you dispose of an ImageJ context using `ij.context().dispose()`, you can subsequently make a new one that can also do ImageJ1ish things. But this does not help with multiprocessing, the whole point of which is to do multiple things at once.)

I suggest you initialize a single ImageJ context _outside_ the multiprocessing loop, and then pass the ImageJ context as an argument to your function.

Finally, after the pool is joined, call `ij.context().dispose()` to free the resources.

**Comment by jluethi** [comment] 2019-05-27 08:27
@ctrueden Thanks for the explanation. So I will initialize outside of the process and run everything in one context.
I am closing the ImageJ1 images with this command (from the Jupyter notebook): `ij.window().clear()`
How do I close an ImageJ2 dataset? For reference, this is my code below. I think that if I can close both ImageJ1 ImagePlus images as well as ImageJ2 datasets, it should be all clear. But I can't find anything on closing ImageJ2 datasets.

Concerning the `ij.context().dispose()`: I would like to use this, but as you say, I could typically call it after the pool is joined. But ImageJ already runs out of memory during the multiprocessing steps. And I can't really call `ij.context().dispose()` while I'm processing multiple images in parallel, without potentially closing other ongoing processes, if everything is run in the same context. Is that correct? If so, I will need to figure out the manual memory handling above.

```
ij.py.run_plugin(plugin, args)
IJ = autoclass('ij.IJ')

# Get the open window with the stitched image
WindowManager = autoclass('ij.WindowManager')
stitched_img = WindowManager.getCurrentImage()

pixel_size_command = "channels=1 slices=1 frames=1 unit=nm pixel_width=" + pixel_size_nm + \
                     " pixel_height=" + pixel_size_nm + " voxel_depth=1.0 global"
IJ.run(stitched_img, "Properties...", pixel_size_command)

# Convert to 8 bit
if eight_bit:
    IJ.run(stitched_img, "8-bit", "")

# Convert it to an ImageJ2 dataset. It was an imageJ1 ImagePlus before and the save function can't handle
# that. See: https://github.com/imagej/pyimagej/issues/35
stitched_img_dataset = ij.py.to_dataset(stitched_img)

output_filename = annotation_name + '.png'
ij.io().save(stitched_img_dataset, str(output_path / output_filename))
# Closing any ImageJ1 windows
ij.window().clear()
```

**Comment by jluethi** [comment] 2019-05-28 12:20
At the moment, solving the memory management for the non-multiprocessing case and running it one process at a time has priority for me.
I have multiple ij.ImagePlus that are loaded  but that I don't know how to dispose, e.g. `stitched_img`. I tried `stitched_img.getWindow().dispose()`, but apparently `stitched_img.getWindow()` returns a NoneType. Also, I have some ImageJ2 dataset (stitched_img_dataset). How do I dispose of those, given that they don't seem to have a window open?? What part of ImageJ is still holding on to them and stopping the Garbage Collection from doing its job? I saw that `net.imagej.DefaultDataset` have an internal delete function, but it's a protected internal function. I tried to trace how it is called, but can't find anything about this.

Just to document this other issue somewhere as well:
Initializing imagej outside of the multiprocessing loop and passing it to the apply_async call leads to a weird issue of multiprocessing not working without giving error message. Here is a small example: If I initialize ij outside of the function (or inside of the function but outside of the loop) and pass it as an argument to apply_async, then apply_async **does not** actually call the function it's supposed to call. If instead of an imagej initialization I just pass an integer, it works fine. The same happens if I pass ij as an input to the class initialization. Any idea how I can trace why imagej is interfering with the multiprocessing here?

------
Example for multiprocessing issue:
```
from multiprocessing import Pool
import imagej

class Test:
    def f(self, i, ij):
        print(i)

    def run(self, ij):
        print('Running')
        with Pool(processes=4) as pool:
            for i in range(10):
                pool.apply_async(self.f, args=(i, ij,))

            pool.close()
            pool.join()

ij = imagej.init('sc.fiji:fiji:2.0.0-pre-10')
# ij = 1

test = Test()
test.run(ij)
```
Output with `ij = imagej.init('sc.fiji:fiji:2.0.0-pre-10')`:
```
Running

Process finished with exit code 0
```
Output with `ij = 1`:
```
Running
0
1
2
4
5
6
3
7
8
9

Process finished with exit code 0
```

**Comment by imagejan** [comment] 2019-05-28 13:43
Concerning IJ1 images (i.e. `ImagePlus` objects), you should be able to call [`imp.close()`](https://javadoc.scijava.org/ImageJ1/index.html?ij/ImagePlus.html) on them.

For IJ2 images (i.e. `Img` and `Dataset`), I don't know if you have to actually close them. The JVM should get rid of them if nothing keeps a handle. But maybe there are bugs in the IJ1<=>IJ2 conversion of the `imagej-legacy` layer??

**Comment by jluethi** [comment] 2019-05-28 14:51
@imagejan Awesome! You made my day! Using the imp.close() on all my IJ1 images decreases memory usage and seems to make my program more stable (haven't had an OutOfMemory exception where it normally comes up). Thank you for taking the time and pointing me towards the close method that maybe should have been obvious but for the best of me I couldn't figure out :)

**Comment by ctrueden** [comment] 2019-05-28 15:37
### Disposal of ImageJ2 image data

`Dataset` objects are considered "in use" when they belong to at least one `ImageDisplay`. When that happens, the `Dataset#incrementReferences()` method is called, which triggers a `DataCreatedEvent` to be fired, which triggers the `ObjectService` to store a hard reference to the dataset. This is useful, e.g., when presenting a dropdown widget to select which `Dataset`(s) to use when executing a particular command.

Conversely, when an image display is closed, the `Dataset#decrementReferences()` method is called, which triggers `DataDeletedEvent` upon reaching 0 references. This triggers the `ObjectService` to remove the `Dataset` from its object index, which (assuming nothing else holds a reference) will allow the `Dataset` to be garbage collected.

It sounds like closing the `ImagePlus` objects solved your memory issue. But if have trouble in future, one thing you can do to check whether your `Dataset` objects are being retained is to ask the `ObjectService`:
```python
Dataset = autoclass('net.imagej.Dataset')
datasets = ij.object().getObjects(Dataset)
for i in range(0, datasets.size()):
    print(datasets.get(i))
```
If you see the list of datasets growing per iteration, then references are being retained.

### Multithreading issues

I am a bit out of my depth here. I was able to reproduce the problem. Here is a version I got working by treating `ij` as a global variable instead of trying to pass it as function argument:

<details><summary>simple_ij_multiprocessing.py</summary>

```python
from multiprocessing import Pool
import imagej

ij = imagej.init('/Applications/Fiji.app')
print(ij.getVersion())

class Test:
    def f(self, i):
        print('In test function')
        print('[{}] {}'.format(i, ij.getVersion()))
        print('Leaving test function')

    def run(self):
        print('Running')
        with Pool(processes=4) as pool:
            for i in range(10):
                print('launching {}'.format(i))
                result = pool.apply_async(self.f, args=(i,))
                print('launched {}'.format(i))

            for i in range(10):
                print('waiting for {}'.format(i))
                print('result of {} = {}'.format(i, str(result.get())))

            print('closing pool')
            pool.close()
            print('joining pool')
            pool.join()
            print('pool joined')

test = Test()
test.run()
```

</details>

And the output of a test run on my system:

<details><summary>program output</summary>

```
Added 384 JARs to the Java classpath.
2.0.0-rc-69/1.52n
Running
launching 0
launched 0
launching 1
launched 1
launching 2
launched 2
launching 3
launched 3
launching 4
launched 4
launching 5
launched 5
launching 6
launched 6
launching 7
launched 7
launching 8
launched 8
launching 9
launched 9
waiting for 0
In test function
In test function
In test function
In test function
[0] 2.0.0-rc-69/1.52n
Leaving test function
[1] 2.0.0-rc-69/1.52n
Leaving test function
[2] 2.0.0-rc-69/1.52n
Leaving test function
In test function
[4] 2.0.0-rc-69/1.52n
Leaving test function
In test function
In test function
[5] 2.0.0-rc-69/1.52n
Leaving test function
In test function
In test function
[7] 2.0.0-rc-69/1.52n
Leaving test function
[6] 2.0.0-rc-69/1.52n
Leaving test function
In test function
[8] 2.0.0-rc-69/1.52n
[9] 2.0.0-rc-69/1.52n
Leaving test function
Leaving test function
result of 0 = None
waiting for 1
result of 1 = None
waiting for 2
result of 2 = None
waiting for 3
result of 3 = None
waiting for 4
result of 4 = None
waiting for 5
[3] 2.0.0-rc-69/1.52n
result of 5 = None
Leaving test function
waiting for 6
result of 6 = None
waiting for 7
result of 7 = None
waiting for 8
result of 8 = None
waiting for 9
result of 9 = None
closing pool
joining pool
pool joined
```

</details>

While developing that, I had some syntax errors, which I was able to discover checking `result.get()`. Without this, the `pool.apply_async` call can conceal errors.

There also might be gotchas or limitations when combining Python multiithreading with pyjnius; I'm not sure. If you continue to have problems, you could try moving your multithreading logic to the Java side, which has first-class multithreading support, as opposed to doing it in Python, which is notoriously bad at multithreading due to its Global Interpreter Lock ([1](https://realpython.com/python-gil/#the-impact-on-multi-threaded-python-programs), [2](http://www.dabeaz.com/python/GIL.pdf)).

Here is an example of doing multithreading using ImageJ scripts:

<details><summary>ij_multithreaded_scripts.py</summary>

```python
import imagej

# Initialize ImageJ.
ij = imagej.init('/Applications/Fiji.app')
print('ImageJ v{}'.format(ij.getVersion()))

# Define a Jython script for performing a computation.
# See: https://imagej.net/Scripting
script = """
#@ double number
#@output double result
from java.lang import Math
result = Math.sqrt(number)
"""

# Run the script multiple times across various input values.
jobs = {}
for number in [1, 4, 9, 16, 25, 36, 49, 100]:
    # Structure the script arguments as a dictionary.
    args = ij.py.to_java({
        'number': number
    })
    # Run the script in a new thread on the Java side.
    # Save a reference to the running job, so we can query it later.
    jobs[number] = ij.script().run('script.py', script, True, args)

for key in jobs:
    job = jobs[key]
    # Block until the script completes execution.
    result = job.get()
    # Print out the result of the execution.
    print('{} = {}'.format(key, result.getOutput('result')))

# Shut down ImageJ.
ij.getContext().dispose()
```

</details>

And output from a sample execution:

<details><summary>program output</summary>

```
Added 384 JARs to the Java classpath.
ImageJ v2.0.0-rc-69/1.52n
[INFO] script:script.py = [[result], [2.0]]
[INFO] script:script.py = [[result], [6.0]]
[INFO] script:script.py = [[result], [5.0]]
[INFO] script:script.py = [[result], [4.0]]
[INFO] script:script.py = [[result], [1.0]]
[INFO] script:script.py = [[result], [10.0]]
[INFO] script:script.py = [[result], [7.0]]
1 = 1.0
4 = 2.0
[INFO] script:script.py = [[result], [3.0]]
9 = 3.0
16 = 4.0
25 = 5.0
36 = 6.0
49 = 7.0
100 = 10.0
```

</details>

**Closed** 2019-05-28 15:44 UTC

**Comment by omidalam** [comment] 2019-06-19 22:37
> For IJ2 images (i.e. `Img` and `Dataset`), I don't know if you have to actually close them. The JVM should get rid of them if nothing keeps a handle. But maybe there are bugs in the IJ1<=>IJ2 conversion of the `imagej-legacy` layer??

I use the following code to open some files one by one, convert them to numpy array and do some processing.
```
files=glob.glob(some_files)
for file_path in files:
    img=ij.io().open(file_path)
    as_np=ij.py.from_java(img)
    some_function(as_np)
```
As the program runs the memory usages increases and then when it reaches a certain level it drops instantly. This cycle continues (ups and down in memory usage) and slows down the run when memory usage is high. 
I believe the problem is that img(s) remain open in JVM and when it goes out of memory it gets rid of them. 
Is there any way to just close them just right after converting to numpy?

**Comment by jluethi** [comment] 2019-06-20 07:40
@omidalam If you only need the image as a numpy array and it's a standard format, consider loading it with something like [opencv](https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_gui/py_image_display/py_image_display.html). This just loads the image as a numpy array.

If it's some special file format or you have other reasons to stay with pyimagej, then closing the java images seems to do the job for me. This closes the Image in ImageJ, thus allowing the JVM to reclaim the memory. You do this by calling `img.close()`

So your loop would be:
```
files=glob.glob(some_files)
for file_path in files:
    img=ij.io().open(file_path)
    as_np=ij.py.from_java(img)
    img.close()
    some_function(as_np)
```

**Comment by omidalam** [comment] 2019-06-20 22:04
@jluethi  The main reason that I'm using ImageJ and not something opencv is the BioFormats package of imageJ.

I tried your approach, but I get the following error.
```
AttributeError: 'net.imagej.DefaultDataset' object has no attribute 'close'
```
As I'm going over the above comments. It seems like the 'close' method only exist for ImageJ1 class and not ImageJ2.
Any other thoughts?

**Comment by jluethi** [comment] 2019-06-21 08:24
@omidalam Check out the answers in the forum: https://forum.image.sc/t/pyimagej-outofmemoryerror-possibility-to-re-initialize/25928/5

**Comment by ctrueden** [comment] 2019-06-22 00:06
@omidalam `Dataset` objects should get garbage collected automatically as needed, but you could try doing things explicitly. Maybe set the Python-side object to `None`, invoke the Python garbage collector, then invoke `System.gc()` a couple of times on the Java side? Let us know if you figure out a solution.

**Comment by alam-shahul** [comment] 2020-08-08 00:48
> Here is an example of doing multithreading using ImageJ scripts:
> 
> ij_multithreaded_scripts.py
> And output from a sample execution:
> 
> program output

I have an example like this, but it doesn't quite work... whenever multiple threads try to run a macro script, I get a threading error:

```
[ERROR] Module threw exception
java.lang.NullPointerException
        at org.scijava.script.ScriptModule.getEngine(ScriptModule.java:105)
        at org.scijava.script.ScriptModule.run(ScriptModule.java:126)
        at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
        at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
        at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
        at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ahg/regevdata/projects/CTS/ImageAnalysis/InSitu_Transcriptomics/cisipy/cisipy/preprocessing/stitcher.py", line 81, in stitch_all_samples
    stitch_single_sample(sample, input_directory, output_directory, imagej_instance, 1)
  File "/ahg/regevdata/projects/CTS/ImageAnalysis/InSitu_Transcriptomics/cisipy/cisipy/preprocessing/stitcher.py", line 124, in stitch_single_sample
    job.get()
  File "jnius/jnius_export_class.pxi", line 1145, in jnius.JavaMultipleMethod.__call__
  File "jnius/jnius_export_class.pxi", line 857, in jnius.JavaMethod.__call__
  File "jnius/jnius_export_class.pxi", line 937, in jnius.JavaMethod.call_method
  File "jnius/jnius_jvm_dlopen.pxi", line 91, in jnius.create_jnienv
jnius.JavaException: JVM exception occurred: java.lang.NullPointerException java.util.concurrent.ExecutionException
```

Here is the essence of my code:

```
def stitch(input_directory, input_filename, output_directory):
    """
    Use the BigStitcher plugin to stitch together the series at input_filepath.

    See Fuse.ijm for the ImageJ macro code.
    """

    # Formatting arguments correctly for ImageJ macro code
    output_directory = str(output_directory)
    input_directory = f'{input_directory}/'

    args = imagej_instance.py.to_java({
      'basePath': input_directory,
      'filename': input_filename,
      'fusePath': output_directory
    })

    print("About to call imagej!")

    stitching_job = imagej_instance.script().run("macro.ijm", STITCHING_MACRO, True, args)

    return stitching_job

   ...

def stitch_single_sample(sample, input_directory, output_directory, parallelize=0):
    rounds = sample["rounds"]
    sample_name = sample["name"]

    sample_input_directory = input_directory / sample_name
    sample_output_directory = output_directory / sample_name
    sample_output_directory.mkdir(exist_ok=True)

    jobs = []
    for round_index, imaging_round in enumerate(rounds, start=1):
        round_directory = ("round%d" % round_index)
        filename = imaging_round["filename"]

        input_filename = (filename)
        output_directory = sample_output_directory / round_directory
        output_directory.mkdir(exist_ok=True)

        job = stitch(sample_input_directory, input_filename, output_directory)
        if parallelize > 0:
            jobs.append(job)
        else:
            #imagej_instance = imagej.init("Fiji.app")
            job.get()

    for job in jobs:
        job.get()
```

Here, I would set `parallelize=1` in `stitch_single_sample` to get pyimagej to parallelize stitching with BigStitcher on the Java side. The `imagej_instance` is initialized before this function and passed down to it. However, this leads to the above error.

I also tried using multiprocessing with a global `imagej_instance` variable; however, this just made pyimagej hang whenever it gets to the `imagej_instance.script().run("macro.ijm", STITCHING_MACRO, True, args)` line.

Any advice?

**Comment by alam-shahul** [comment] 2020-08-08 01:41
> ### Multithreading issues
> I am a bit out of my depth here. I was able to reproduce the problem. Here is a version I got working by treating `ij` as a global variable instead of trying to pass it as function argument:
> 
> simple_ij_multiprocessing.py
> And the output of a test run on my system:
> 
> program output
> While developing that, I had some syntax errors, which I was able to discover checking `result.get()`. Without this, the `pool.apply_async` call can conceal errors.

Is there any reason why the ImageJ instance has to be a global variable for this to work? That structure doesn't quite work for my application (I'm building a pip module and the user has to pass the path to their Fiji installation as an argument to a function).
