### ISSUE TITLE
Converting a Java String to a Python String creates an empty File

### ISSUE THREAD

**Issue by gselzer** [imagej/pyimagej#160] opened 2022-01-05 15:40 UTC
@ctrueden  @elevans  here is an MCVE:

```python
import os
import imagej
from scyjava import config, jimport

config.add_option(f'-Dimagej.dir={os.getcwd()}')
ij = imagej.init()

String = jimport('java.lang.String')

s = String("foo")

# This is the problematic line
ij.py.from_java(s)
```

This seems to happen with SciJava Common versions 2.87.0 and 2.87.1

**Comment by elevans** [comment] 2022-01-05 15:52
From the PyImageJ layer the bug is triggered when `from_java` checks what the incoming data type is with `ij.convert().supports()`

```python
if not sj.isjava(data): return data
try:
    if self._ij.convert().supports(data, Dataset): # triggers bug
```

**Comment by ctrueden** [comment] 2022-01-05 16:13
Thanks @elevans. I was able to reproduce this in pure Java using jgo from the command line:
```
$ jgo repl
Welcome to the SciJava REPL!
...
language -> Groovy
> s = "asdf"
asdf
> new java.io.File(s).exists()
false
> ij.convert().supports(s, net.imagej.Dataset.class)
false
> new java.io.File(s).exists()
true
```

**Comment by ctrueden** [comment] 2022-01-05 16:21
The bug-fix I was thinking of was scijava/scijava-common@c4cb3a71f6e5c02d78d27bcee728adb096f579ef. But this bug-fix was included in scijava-common 2.87.0:
```
$ git tag --contains c4cb3a71f6e5c02d78d27bcee728adb096f579ef
scijava-common-2.87.0
scijava-common-2.87.1
scijava-common-2.87.2
```
And looking at the patch, this doesn't actually address the problem I mentioned where files get created too eagerly. I thought we had done something to prevent this issue, but now I'm not sure.

**Comment by ctrueden** [comment] 2022-01-05 16:52
The problem is caused by SCIFIO's `FileToDatasetConverter` and `StringToDatasetConverter`, which attempts to check, for a given `Location` (in this case a `FileLocation`), whether SCIFIO can open it. If SCIFIO can open it, then it can be converted to a `Dataset`, and those converters report `true` for `canConvert`/`supports`.

I verified that nothing in the framework itself is creating the file in question—rather, one of the SCIFIO format plugins is doing it, when [this code](https://github.com/scifio/scifio/blob/scifio-0.41.2/src/main/java/io/scif/services/DefaultDatasetIOService.java#L87-L88) is called.

Here is a more minimal example with jgo:
```
$ jgo org.scijava:scijava-common:2.87.1:org.scijava.script.ScriptREPL+org.scijava:scripting-groovy:0.4.1+io.scif:scifio:0.41.2
...
language -> Groovy
> scifio.datasetIO().canOpen("asdf")
false
> new java.io.File("asdf").exists()
true
```

Next steps:
* Test with the latest SCIFIO release.
* If still broken, debug into `FormatService.getFormat`.

**Comment by imagejan** [comment] 2022-01-06 08:25
Related: https://github.com/scifio/scifio/issues/415, which is part of `scifio-0.43.0` and later.

**Comment by ctrueden** [comment] 2022-02-02 19:06
I am going to close this issue, since there is no more action required on the pyimagej side.

**Closed by ctrueden** 2022-02-02 19:06 UTC
