### ISSUE TITLE
error: Class not found b'net/imagej/ImageJ'

### ISSUE THREAD

**Issue by Eloise2000** [imagej/pyimagej#90] opened 2020-11-10 10:02 UTC
I followed the documents to use ImageJ in Python.
I created a new environment in conda with openjdk=8 and python=3.7 and installed pyjnius=1.2.0, imagej=0.3.1 and imglyb=0.3.5.
However, I got an error 
```py
  File ".\tttest.py", line 21, in <module>
    ij = imagej.init('D:\Eloise\Fiji.app', headless=False, new_instance=True)
  File "C:\Users\p'l\.conda\envs\pyimagej\lib\site-packages\imagej\imagej.py", line 130, in init
    ImageJ = autoclass('net.imagej.ImageJ')
  File "C:\Users\p'l\.conda\envs\pyimagej\lib\site-packages\jnius\reflect.py", line 159, in autoclass
    c = find_javaclass(clsname)
  File "jnius\jnius_export_func.pxi", line 26, in jnius.find_javaclass
jnius.JavaException: Class not found b'net/imagej/ImageJ
```
with the code:
```
import imagej
ij = imagej.init('D:\Eloise\Fiji.app', headless=False, new_instance=True)
```
Moreover, I specifically set the path in python file ahead:
```
import os

os.environ["JAVA_HOME"] = "C:/Program Files/Java/jdk1.8.0_271"
os.environ["JDK_HOME"] = "C:/Program Files/Java/jdk1.8.0_271"
os.environ["JRE_HOME"] = "C:/Program Files/Java/jre1.8.0_271"
os.environ["PYJNIUS_JAR"] = "C:/Users/p'l/.conda/envs/pyimagej/share/pyjnius/pyjnius.jar"
os.getenv("JAVA_HOME")
os.getenv("JDK_HOME")
os.getenv("JRE_HOME")
os.getenv("PYJNIUS_JAR")
```

**Comment by ctrueden** [comment] 2020-11-30 07:00
Sorry for the delay in reply, @Eloise2000. I notice you are installing `imagej=0.3.1` rather than `pyimagej=0.5.0`. The `imagej` package was the old name, and that version won't work with the other newer components.

Also: we are approaching a new release of PyImageJ, which substantially changes how the Java bridge works under the hood. I’ll reply back here again once that release is ready for you to test.

**Comment by ctrueden** [comment] 2020-12-01 05:40
@Eloise2000 I'm going to close this, because I think the problem is that you were installing the old package `imagej` instead of the new package `pyimagej`. Sorry for the rename but the conda-forge folks insisted on it. FYI, version 1.0.0 of pyimagej is now released on PyPI (will propagate to conda-forge very soon) so you can also try that if you like. :smile:

**Closed by ctrueden** 2020-12-01 05:40 UTC
