### ISSUE TITLE
imagej.init(path_to_Fiji.app_file) does not work anymore

### ISSUE THREAD

**Issue by kazemSafari** [imagej/pyimagej#91] opened 2020-11-11 20:58 UTC
I installed pyimagej via conda using the instructions provided by your website. I also downgraded imglyb to 0.3.5 and pyjnius to 1.2.0.
My pyimagej was working fine for a while until today. Now when i initialize it:
```
import imagej
ij = imagej.init('.../Fiji.app', headless=False)
```
It raise the following error:
```
  ij = imagej.init('.../Fiji.app', headless=False)
  File ".../anaconda3/envs/pyimagej/lib/python3.7/site-packages/imagej/imagej.py", line 131, in init
    ij = ImageJ()
  File "jnius/jnius_export_class.pxi", line 256, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 343, in jnius.JavaClass.call_constructor
  File "jnius/jnius_utils.pxi", line 91, in jnius.check_exception
jnius.JavaException: JVM exception occurred: Invalid service: sc.fiji.filamentdetector.gui.GUIStatusService
```

Can you please help resolve this issue. Thank you.

**Comment by kazemSafari** [comment] 2020-11-11 21:12
I found this solution to work for me:
[filamentdetector](https://forum.image.sc/t/fiji-fails-to-launch-after-update/44582/2)

**Comment by ctrueden** [comment] 2020-12-01 04:56
Thanks @kazemSafari for posting the workaround. This is a problem with Fiji currently, not a bug in PyImageJ, and so I'm closing this. The proper fix will probably be to ship a newer FilamentDetector plugin that doesn't suffer from this issue.

**Closed by ctrueden** 2020-12-01 04:56 UTC
