### ISSUE TITLE
Failed to convert xarray to ImagePlus

### ISSUE THREAD

**Issue by oeway** [imagej/pyimagej#167] opened 2022-02-04 11:16 UTC
Hi, I have the following code for converting xarray to imagePlus (since I want to display the image so it can be accessed in imagej1 macro):

(pyimagej version: 1.0.2, fiji distribution: https://downloads.imagej.net/fiji/archive/20201104-1356/fiji-linux64.zip)
```python
ImagePlus = sj.jimport("ij.ImagePlus")
da = xr.DataArray(
    data=np.zeros([512, 512],  dtype='uint16'),
    dims=['x', 'y'],
    attrs={},
   name="inputImage",
)
print('===========>', da)
dataset = ij.py.to_java(da)
print('===img input===>', dataset)
imgp = ij.convert().convert(dataset, ImagePlus)
print('===img output===>', imgp)
```

However, the output after conversion becomes None:
```
imagej_1  | ===========> <xarray.DataArray 'inputImage' (x: 512, y: 512)>
imagej_1  | array([[14, 19, 22, ..., 23, 22,  7],
imagej_1  |        [19, 17, 17, ..., 24, 18, 20],
imagej_1  |        [15, 14, 22, ..., 19, 21,  9],
imagej_1  |        ...,
imagej_1  |        [38, 34, 38, ..., 31, 33, 29],
imagej_1  |        [40, 37, 29, ..., 34, 28, 35],
imagej_1  |        [33, 28, 27, ..., 20, 33, 37]], dtype=uint16)
imagej_1  | Dimensions without coordinates: x, y
imagej_1  | ===img input===> <unnamed data>
imagej_1  | ===img output===> None
```

And also, it seems the xarray name is not passed to the dataset after the to_java conversion (since it prints `unnamed data`), maybe it would be nice to name it the same after conversion?

**Comment by ctrueden** [comment] 2022-10-31 18:43
@oeway Sorry for the long delay in reply! I cannot reproduce the None conversion problem with PyImageJ on the current master branch:
```
===========> <xarray.DataArray 'inputImage' (x: 512, y: 512)>
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint16)
Dimensions without coordinates: x, y
===img input===> <unnamed data>
===img output===> img["" (-2), 16-bit, 512x512x1x1x1]
```

### Propagation of image name/title

I do however see that as you noticed, xarray name is not being propagated to `Dataset` name:
```python
>>> da.name
'inputImage'
>>> dataset.getName()
>>> imgp.getTitle()
''
```

But if the `Dataset` *does* have a name, then it gets propagated to the `ImagePlus`'s title:
```python
>>> dataset.setName("woop")
>>> imgp = ij.convert().convert(dataset, ImagePlus)
>>> imgp.getTitle()
'woop'
```

I filed #232 to track this issue.

### Simpler way to convert to `ImagePlus`

Note that PyImageJ now has a convenience function `ij.py.to_imageplus` which can be used to make an `ImagePlus` directly from other kinds of images, including both `Dataset`s and xarrays:
```
>>> imgp = ij.py.to_imageplus(dataset)
Operating in headless mode - the original ImageJ will have limited functionality.
>>> imgp.getTitle()
'woop'
>>> imgp = ij.py.to_imageplus(da)
>>> imgp.getTitle()
''
```

### Be careful about dimension order

Finally, the dimensional axis ordering is tricky here, in case you didn't already know. I slightly altered your example to make a 512x384 image instead of a square 512x512 one, so that we can see what happens to each axis more clearly. The conversion from xarray to `Dataset` looks like:
```
>>> da.dims
('x', 'y')
>>> dataset.dims
('Y', 'X')
>>> da.shape
(512, 384)
>>> dataset.shape
(384, 512)
```
The dims are flipped as desired when going from Python to Java. This is explained in detail in [6.7 Passing image data from Python to Java](https://pyimagej.readthedocs.io/en/latest/06-Working-with-Images.html#passing-image-data-from-python-to-java); in a nutshell:

> PyImageJ makes an effort to respect the scikit-image dimension order convention where applicable, including ***reordering dimensions between ImageJ2 style and scikit-image style*** when translating images between worlds.

As an aside here: using `('x', 'y')` for your xarray here is backwards from normal Python... you should probably use `('y', 'x')` instead if possible.

Anyway, so far so good. But what about the `ImagePlus`? In original ImageJ, the only supported dimension order is XYCZT, so when converting from `Dataset` or `xarray` to `ImagePlus` here, we see this:

```
>>> imgp.dims
('X', 'Y')
>>> imgp.shape
(512, 384)
```

So PyImageJ *does* give you an `ImagePlus` with the correct axes in the correct places for `ImagePlus`. It's just a little convoluted getting there!

I'm going to close this issue, since I think everything is either resolved, or explained, or tracked in a separate issue now. But @oeway you are welcome to reopen if this conversion failure persists for you!

**Closed by ctrueden** 2022-10-31 18:43 UTC
