### ISSUE TITLE
Potential performance improvement of rai_to_numpy

### ISSUE THREAD

**Issue by haesleinhuepf** [imagej/pyimagej#46] opened 2019-10-27 16:31 UTC
Hi all,

I recently received an [issue report](https://github.com/clij/clijpy/issues/2) from a user who experienced slow performance of the `rai_to_numpy` method. I was able to trace it down to this [line](https://github.com/imagej/pyimagej/blob/master/imagej/imagej.py#L167) which copies content of an RAI to another RAI:

```
self._ij.op().run("copy.rai", self.to_java(result), rai)
```

I implemented a [workaround](https://github.com/clij/clij-advanced-filters/blob/master/src/main/java/net/haesleinhuepf/clijx/CLIJx.java#L81) which does that copy operation straight forward:
```
Cursor<RealType> cursor = Views.iterable(rai).cursor();
Cursor<RealType> target_cursor = Views.iterable(target).cursor();

while(cursor.hasNext() && target_cursor.hasNext()) {
    target_cursor.next().set(cursor.next());
}
```

Would it be possible to implement something similar in pyimagej? IMHO performance is key when sending images between python and imagej universes....

Cheers,
Robert

**Comment by imagejan** [comment] 2019-10-28 11:19
Hi Robert,
isn't this a performance problem with the underlying `copy.rai` op implementation, and should therefore even better be fixed on the `imagej-ops` level?

**Comment by haesleinhuepf** [comment] 2019-10-28 12:57
Not sure. Is it a problem of the particular op or the ops discovery mechanism?
![image](https://user-images.githubusercontent.com/12660498/67680054-c8bad000-f98a-11e9-93a2-8e4bc0df86ae.png)

It looks a bit like both. Give it a try ;-)
https://github.com/clij/clijpy/blob/speedup_test_rai_to_numpy/python/clijpy_demo.ipynb

**Comment by ctrueden** [comment] 2019-10-29 23:52
Ops matching performance is improved with the new scijava-ops framework. We can revisit this issue after imagej-ops has migrated to that framework.

**Comment by ctrueden** [comment] 2019-11-13 18:39
I [posted on the Image.sc Forum](https://forum.image.sc/t/best-way-to-copy-data-between-imglib2-images/31316) asking if ImgLib2 has a built-in utility method for copying data from one image to another.

But we still need to know more details about which scenarios have bad performance, and how bad. E.g. if the performance problem is in Ops, then we _need_ to fix it in Ops.

**Comment by haesleinhuepf** [comment] 2019-11-20 18:22
Hey @ctrueden ,

> benchmark this in a more meaningful way, I suggest at least 10 iterations

good point!

> E.g. if the performance problem is in Ops, then we need to fix it in Ops.
 
I would vote for fixing this in pyimagej and not waiting for a fix in Ops. I did some more benchmarks to see how fast conversion gets after a while. Feel free to [reproduce them](https://github.com/clij/clijpy/blob/master/python/benchmark_clijx_pull.ipynb).

That's the most important code block:
```
# pull image back from GPU
RandomAccessibleInterval = autoclass('net.imglib2.RandomAccessibleInterval');
ij_img_result = clijx.convert(labelled_without_edges, RandomAccessibleInterval);
imageplus_result = clijx.pull(labelled_without_edges);
# 
# convert to numpy/python
import time
def getTime():
    return int(round(time.time() * 1000))

def clijx_pull(buffer):
    import numpy
    numpy_image = numpy.zeros([buffer.getWidth(), buffer.getHeight(), buffer.getDepth()])
    wrapped = ij.py.to_java(numpy_image);
    clijx.pullToRAI(buffer, wrapped); # see https://github.com/clij/clij-advanced-filters/blob/master/src/main/java/net/haesleinhuepf/clijx/CLIJx.java#L87 
    return numpy_image

def my_rai_to_numpy(rai):
    result = ij.py.new_numpy_image(rai)
    CopyRAI = autoclass('net.imagej.ops.copy.CopyRAI');
    ij.py._ij.op().run(CopyRAI, ij.py.to_java(result), rai)
    return result

num_iterations = 100;

way1timings = np.zeros(num_iterations);
way2timings = np.zeros(num_iterations);
way3timings = np.zeros(num_iterations);

for it in range(0, num_iterations):
    #########################################################
    # Way 1
    millis = getTime();
    np_arr_result = clijx_pull(labelled_without_edges);
    way1timings[it] = (getTime() - millis)

    #########################################################
    # Way 2
    ij_img_result = clijx.convert(labelled_without_edges, RandomAccessibleInterval); # we exclude clij routines for benchmarking conversion if possible
    millis = getTime();
    np_arr_result = ij.py.rai_to_numpy(ij_img_result);
    way2timings[it] = (getTime() - millis)

    #########################################################
    # Way 3
    ij_img_result = clijx.convert(labelled_without_edges, RandomAccessibleInterval); # we exclude clij routines for benchmarking conversion if possible
    millis = getTime();
    np_arr_result = my_rai_to_numpy(ij_img_result);
    way3timings[it] = (getTime() - millis)
    
    #########################################################
print("Way 1: " + str(np.mean(way1timings)) + " +- " + str(np.std(way1timings)));
print("Way 2: " + str(np.mean(way2timings)) + " +- " + str(np.std(way2timings)));
print("Way 3: " + str(np.mean(way3timings)) + " +- " + str(np.std(way3timings)));
```

And that's its output on my Intel i7-8750H with DDR4 memory when processing blobs.png:
```
Way 1: 1.67 +- 0.4910193478876367
Way 2: 7.61 +- 0.9369631796394136
Way 3: 3.51 +- 0.8306021911842033
```

As blobs is pretty small, I also tried with a 121 MB file:
```
Way 1: 610.1 +- 20.290145391297717
Way 2: 218.5 +- 118.87998149394204
Way 3: 211.4 +- 90.92106466600576
```

As you suspected, it's not so easy to say which method copies the fastest. Can we anyway [push the parallel copy forward](https://github.com/imglib/imglib2/pull/237)? Maybe, we can also put my `my_rai_to_numpy` workaround from above [into pyimagej](https://github.com/imagej/pyimagej/blob/master/imagej/imagej.py#L173)? It is obviously faster in case of small images and similarily fast with large images...

Furthermore, I repeat my offer: If you show me how to deploy pyimagej, I would happy to help maintaining it.

Cheers,
Robert

**Comment by ctrueden** [comment] 2019-11-25 20:53
> If you show me how to deploy pyimagej, I would happy to help maintaining it.

Sure. Will you have a day during the CSBD hackathon for us to go over it? That will be easier for me than trying to do it remotely before that.

**Comment by haesleinhuepf** [comment] 2019-11-26 14:13
That would be great!

**Comment by ctrueden** [comment] 2020-01-23 17:54
I added a method `net.imagej.util.Images.copy(src, dest)` to imagej-common, which pyimagej will be able to use instead of calling ops. It leans on `LoopBuilder` and its `multiThreaded()` feature. The `Images.copy` method is part of imagej-common 0.30.0, released just now. Once pom-scijava catches up, we'll be able to switch over to it in the pyimagej code. I did not benchmark it, but I'll be surprised if it's slower in the common case. In special cases though it could be a lot slower, since we won't be using Ops anymore, and one of the advantages of Ops is automatic special-casing for performance depending on the types. Once the new SciJava Ops is released, we can look at moving pyimagej back over to an Ops-based invocation for image copies.

**Comment by ctrueden** [comment] 2020-12-01 06:16
Using `Images.copy` didn't make it into the 1.0.0 release, but should be straightforward to try it out now, and if faster, then switch it over in the pyimagej codebase and make a patch release.

**Comment by elevans** [comment] 2021-03-29 19:59
@ctrueden @haesleinhuepf 

I've pushed a branch where I've added a new method, `new_rai_to_numpy` using @ctrueden's `Image.copy` method. Long story short, its faster on my end. Can someone else try it out? The changes are on the `rai-copy-speed` branch.

My results comparing them with `time.process_time()` inserted around the `rai_to_numpy` and `new_rai_to_numpy` methods. I'm not sure if this the appropriate measurement but stackoverflow said it was okay :).

```python
>>> import imagej
>>> ij = imagej.init()
>>> img = ij.io().open('test_stack.tif') # a small 3D z-stack
>>> img
<java object 'net.imagej.DefaultDataset'>
>>> for i in range(10):
...     x = ij.py.rai_to_numpy(img)
...
Elapsed cpu time: 11.781962492000005
Elapsed cpu time: 3.862406704999998
Elapsed cpu time: 0.9409388720000038
Elapsed cpu time: 0.9219799149999943
Elapsed cpu time: 1.0656797219999987
Elapsed cpu time: 0.9709097549999939
Elapsed cpu time: 1.0696743630000043
Elapsed cpu time: 1.0387322309999973
Elapsed cpu time: 1.087515769999996
Elapsed cpu time: 1.0664980859999957
>>> for i in range(10):
...     y = ij.py.new_rai_to_numpy(img)
...
Elapsed cpu time: 2.269988717000004
Elapsed cpu time: 0.08695155300000579
Elapsed cpu time: 0.09026932599999782
Elapsed cpu time: 0.09899085799999341
Elapsed cpu time: 0.09891915699999743
Elapsed cpu time: 0.12921210100000735
Elapsed cpu time: 0.08771793699999364
Elapsed cpu time: 0.08889969899999528
Elapsed cpu time: 0.09478311199998757
Elapsed cpu time: 0.092664900000002
>>> old = ij.py.rai_to_numpy(img)
Elapsed cpu time: 0.7312777629999943
>>> new = ij.py.new_rai_to_numpy(img)
Elapsed cpu time: 0.097611950000001
>>>(old==new).all() # test both arrays are the same
True
```

It looks like after the first copy its caching the image (I'm not sure how it works), but even so `Image.copy` is faster.

**Comment by ctrueden** [comment] 2021-05-10 14:47
Here are the results on my system:

<details><summary>Small image</summary>

```python
>>> small = ij.io().open('/home/curtis/data/t1-head.tif')
>>> for d in range(small.numDimensions()): print(small.dimension(d))
... 
256
256
129
>>> for i in range(10): ij.py.new_rai_to_numpy(small)
... 
Elapsed cpu time: 0.8251261280000008
Elapsed cpu time: 0.1823608020000016
Elapsed cpu time: 0.1835499039999995
Elapsed cpu time: 0.17489815399999742
Elapsed cpu time: 0.16482523799999882
Elapsed cpu time: 0.1698506980000012
Elapsed cpu time: 0.17060083299999818
Elapsed cpu time: 0.16544053999999875
Elapsed cpu time: 0.17198222900000104
Elapsed cpu time: 0.1628066230000016
>>> for i in range(10): ij.py.rai_to_numpy(small)
... 
Elapsed cpu time: 1.5365566070000014
Elapsed cpu time: 0.44610043900000207
Elapsed cpu time: 0.29392972800000194
Elapsed cpu time: 0.32376065600000103
Elapsed cpu time: 0.32973326699999816
Elapsed cpu time: 0.3078388260000011
Elapsed cpu time: 0.31005844200000254
Elapsed cpu time: 0.3105525920000005
Elapsed cpu time: 0.3101193209999984
Elapsed cpu time: 0.2740601060000003
>>>
```

</details>

<details><summary>Large image</summary>

```python
>>> large = ij.io().open('/home/curtis/data/dub.ome.tif')
>>> for d in range(large.numDimensions()): print(large.dimension(d))
... 
768
512
2805
>>> for i in range(10): ij.py.new_rai_to_numpy(large)
... 
Elapsed cpu time: 20.825933725000006
Elapsed cpu time: 20.512984893000002
Elapsed cpu time: 20.581009893
Elapsed cpu time: 20.562239479
Elapsed cpu time: 20.635273683999998
Elapsed cpu time: 20.551274188999997
Elapsed cpu time: 20.615517125999986
Elapsed cpu time: 20.654124486
Elapsed cpu time: 20.461514861000012
Elapsed cpu time: 20.556031767999997
>>> for i in range(10): ij.py.rai_to_numpy(large)
... 
Elapsed cpu time: 24.751310029000024
Elapsed cpu time: 22.664768580999976
Elapsed cpu time: 22.530859324000005
Elapsed cpu time: 22.670824746999983
Elapsed cpu time: 22.68788665599999
Elapsed cpu time: 22.597186340999997
Elapsed cpu time: 22.713653993000037
Elapsed cpu time: 22.717955104999987
Elapsed cpu time: 22.827708132999987
Elapsed cpu time: 22.369467750000013
>>> 
--------------------------------------------------------------------------------------------
>>> for i in range(10): ij.py.new_rai_to_numpy(img)
... 
Elapsed cpu time: 22.370642683999996
Elapsed cpu time: 21.76115547
Elapsed cpu time: 21.717881075999998
Elapsed cpu time: 21.716643778000005
Elapsed cpu time: 21.814347901999994
Elapsed cpu time: 21.695295704999978
Elapsed cpu time: 21.836572990999997
Elapsed cpu time: 21.829423742000017
Elapsed cpu time: 21.738652058000014
Elapsed cpu time: 21.688648736000005
>>> for i in range(10): ij.py.rai_to_numpy(img)
... 
Elapsed cpu time: 26.025339066000015
Elapsed cpu time: 21.256342001999997
Elapsed cpu time: 21.22431271900001
Elapsed cpu time: 21.142290032999995
Elapsed cpu time: 21.18565523999996
Elapsed cpu time: 20.798891782
Elapsed cpu time: 21.337041446
Elapsed cpu time: 21.377844055000025
Elapsed cpu time: 21.312686315999997
Elapsed cpu time: 21.028333120000013
>>> for d in range(img.numDimensions()): print(img.dimension(d))
... 
256
256
129
>>> for i in range(10):
...   ij.py.rai_to_numpy(img)
... 
Elapsed cpu time: 1.3873114809999976
Elapsed cpu time: 0.5053256929999996
Elapsed cpu time: 0.3823747250000018
Elapsed cpu time: 0.3794178850000023
Elapsed cpu time: 0.32428832000000085
Elapsed cpu time: 0.3225414930000028
Elapsed cpu time: 0.3222183479999998
Elapsed cpu time: 0.34042292600000224
Elapsed cpu time: 0.2934665729999999
Elapsed cpu time: 0.3190974450000006
>>> ij.py.new_rai_to_numpy(img)
Elapsed cpu time: 0.7661938050000003
>>> for i in range(10): ij.py.new_rai_to_numpy(img)
... 
Elapsed cpu time: 0.23866378399999988
Elapsed cpu time: 0.1795941059999997
Elapsed cpu time: 0.16556635300000266
Elapsed cpu time: 0.19881129199999847
Elapsed cpu time: 0.15533051799999953
Elapsed cpu time: 0.1607467920000012
Elapsed cpu time: 0.15948870799999781
Elapsed cpu time: 0.1759843000000032
Elapsed cpu time: 0.19089132599999914
Elapsed cpu time: 0.17449670599999934
>>>
```

</details>

So yeah, it's better. Especially for small images, but also modestly better for large ones.

**Comment by ctrueden** [comment] 2021-07-26 04:12
@elevans Any progress on this?

**Comment by elevans** [comment] 2021-07-29 15:22
@ctrueden I added version checking to https://github.com/scijava/scyjava/commit/f033a100a23fcf8766bde813eeec753c12aa2b1c  so I can check which version of `imagej-common` is active and supports the fast copy https://github.com/imagej/pyimagej/commit/843d405b11679d782cd7158ae4156bbd3f590c4c like in your example.

I tested it on my system and it works as intended.

**Closed** 2021-11-16 15:33 UTC
