### ISSUE TITLE
Example for using RoiManager from Python (not Jython)

### ISSUE THREAD

**Issue by alphacentauri12** [imagej/pyimagej#55] opened 2019-12-12 10:38 UTC
Can anybody please give a short example of how to start and use the RoiManager from 'pure' Python (not Jython)?

**Comment by ctrueden** [comment] 2020-01-15 18:44
@alphacentauri12 Since this is not a bug report, you'd probably get more and better responses by posting your question on the [Image.sc Forum](https://forum.image.sc) with tags `imagej`, `pyimagej` and `roi-manager`.

Regarding the `ij.plugin.frame.RoiManager` functionality: that class does not work headless. So you will need to spin up your ImageJ context using `imagej.init(headless=False)`. If you are still having problems after doing that: can you post a code sample with explanation what doesn't work, and what you want to have happen instead?

**Comment by ctrueden** [comment] 2022-02-14 19:21
Addressing #172 will create a notebook showcasing how to work with the `RoiManager` while _not_ headless, at which point I will feel comfortable closing this issue as well.

**Comment by elevans** [comment] 2022-10-31 16:27
Following up on this issue. We created two similar examples that utilize the `ROIManager` with PyImageJ. In the `doc/examples` directory of the PyImageJ repo (and also online [here](https://pyimagej.readthedocs.io/en/latest/use_cases.html) on the pyimagej ReadTheDocs documentation site) are two python scripts which use the `ROIManager` in finding blobs in a sample image.

The first script, `blob_detection_interactive.py` calls the `ROIManager` window and populates it with blob ROIs. The second example script, `blobl_detection_xvfb.py`  which does the same analysis but utilizes the X Virtual framebuffer to simulate a GUI environment. This is necessary as the the `ROIManager` **does not** work in true headless environments.

For more information on using headless PyImageJ and using xvfb checkout the [Using PyImageJ without a screen](https://pyimagej.readthedocs.io/en/latest/Headless.html) document.

**Closed by elevans** 2022-10-31 16:27 UTC
